services:
  db:
    image: postgres:15-alpine
    container_name: buildwise-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: buildwise_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: BuildWised@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent volume
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local