version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: buildwise-postgres
    environment:
      POSTGRES_DB: buildwise_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: BuilWised@123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MinIO for file storage
  minio:
    image: minio/minio:latest
    container_name: buildwise-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  # Your Spring Boot Backend (NEW!)
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: buildwise-backend
    environment:
      # Database connection - use container names
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/buildwise_db?stringtype=unspecified
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: BuilWised@123
      # MinIO connection
      MINIO_ENDPOINT: http://minio:9000
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8082:8082"
    networks:
      - app-network

volumes:
  postgres_data:
  minio_data:

networks:
  app-network:
    driver: bridge