
spring:
  datasource:
    url: jdbc:postgresql://192.168.1.2:5042/buildwise_db?stringtype=unspecified
    username: ${buildwise.database.username}
    password: ${buildwise.database.password}

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  mail:
    host: ${buildwise.mail.host}
    port: ${buildwise.mail.port}
    username: ${buildwise.mail.username}
    password: ${buildwise.mail.password}
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
          ssl:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        debug: false

app:
  jwt-secret: ${buildwise.jwt.secret}

api:
  sms-url: ${buildwise.sms.url}
  sms-password: ${buildwise.sms.password}
  sms-username: ${buildwise.sms.username}
  sms-sender: ${buildwise.sms.sender}

frontend:
  base-url: ${buildwise.frontend.base-url}

minio:
  endpoint: http://192.168.1.2:9000
  access-key: ${buildwise.minio.access-key}
  secret-key: ${buildwise.minio.secret-key}
  bucket-prefix: org-
  secure: false

logging:
  level:
    com.buildwise: INFO
    org.springframework.cloud.vault: DEBUG