spring:
  application:
    name: BuildWise-BACKEND

  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/buildwise_db?stringtype=unspecified
    username: postgres
    password: BuilWised@123
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Mail Configuration
  mail:
    host: mail.privateemail.com
    port: 465
    username: office@kibuti.co
    password: Office@2030
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
          ssl:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        debug: false

  # Other Spring Settings
  threads:
    virtual:
      enabled: true

  jackson:
    generator:
      write-bigdecimal-as-plain: true

# Server Configuration
server:
  port: 8082
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: text/html, text/plain, application/json, application/xml

# Application Settings
app:
  jwt-secret: b79943ecd429541f7960138c5a8d53c926f8fe27c41354e8ced0d73fb5269353
  jwt-expiration-milliseconds: 604800000
  jwt-refresh-token:
    expiration-days: 365  # This was missing!

# SMS API
api:
  sms-url: https://messaging-service.co.tz/api/sms/v1/text/single
  sms-password: "@Jesus2020"
  sms-username: edwingudfriend
  sms-sender: "KIBUTI BOT"

# OTP Configuration
otp:
  expire_time:
    minutes: 10

# Frontend
frontend:
  base-url: http://localhost:5175

# MinIO
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin123
  bucket-prefix: org-
  secure: false

# Logging
logging:
  level:
    com.buildwise: DEBUG

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always